{% set version = "1.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinytest
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinytest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinytest/shinytest_{{ version }}.tar.gz
  sha256: 45eac3f3e43086f3c4be4e4427f09953ac8183630cee10ccbcef90dcc1fb8635

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-assertthat
    - r-callr >=2.0.3
    - r-crayon
    - r-debugme
    - r-digest
    - r-htmlwidgets
    - r-httpuv
    - r-httr
    - r-jsonlite
    - r-parsedate
    - r-pingr
    - r-rematch
    - r-rstudioapi >=0.8.0.9002
    - r-shiny >=1.0.4
    - r-testthat >=1.0.0
    - r-webdriver >=1.0.5
    - r-withr
    - phantomjs
  run:
    - r-base
    - r-r6
    - r-assertthat
    - r-callr >=2.0.3
    - r-crayon
    - r-debugme
    - r-digest
    - r-htmlwidgets
    - r-httpuv
    - r-httr
    - r-jsonlite
    - r-parsedate
    - r-pingr
    - r-rematch
    - r-rstudioapi >=0.8.0.9002
    - r-shiny >=1.0.4
    - r-testthat >=1.0.0
    - r-webdriver >=1.0.5
    - r-withr
    - phantomjs

test:
  commands:
    - $R -e "library('shinytest')"           # [not win]
    - "\"%R%\" -e \"library('shinytest')\""  # [win]

about:
  home: https://github.com/rstudio/shinytest
  license: MIT
  summary: For automated testing of Shiny applications, using a headless browser, driven through 'WebDriver'.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shinytest
# Title: Test Shiny Apps
# Version: 1.3.1
# Authors@R: c( person("Winston", "Chang", role = c("aut", "cre"), email = "winston@rstudio.com"), person("Gabor", "Csardi", role = "aut", email = "gabor@rstudio.com") )
# Description: For automated testing of Shiny applications, using a headless browser, driven through 'WebDriver'.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/rstudio/shinytest
# BugReports: https://github.com/rstudio/shinytest/issues
# RoxygenNote: 6.1.1
# Imports: assertthat, digest, crayon, debugme, parsedate, pingr, callr (>= 2.0.3), R6, rematch, httr, shiny (>= 1.0.4), testthat (>= 1.0.0), utils, webdriver (>= 1.0.5), htmlwidgets, jsonlite, withr, httpuv, rstudioapi (>= 0.8.0.9002)
# Suggests: rmarkdown, flexdashboard
# Encoding: UTF-8
# SystemRequirements: PhantomJS (http://phantomjs.org/)
# NeedsCompilation: no
# Packaged: 2019-05-03 22:10:28 UTC; cpsievert
# Author: Winston Chang [aut, cre], Gabor Csardi [aut]
# Maintainer: Winston Chang <winston@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-05-06 19:40:02 UTC
