appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: V9opjB2GK8wM3vRsz11fS63Jo5OLWMqbxbw57CReSI3WZruQeY1kmQA2FtVYKLrhCm6lV088vyknN9H5E1JNH2HD3dHCrfRvltKYAb7krTUASZ/O57a245srTiJWgVij07oFAVE1wBaIu9Gu5OXcIAV0FiZhGDV9QH9rAcx+Ob/WbkAjGdOjajr98HxSpaX1daqzfMv8UBXPXTSqsDTOaxaYmwV9Cj/6qhAzTeHyCZdYveUrZX0VNrjNWpjWI2PTJjX5Kz1hxO3LbffkFnovdssgGTtoFxbhuIyroGzIADGar/TkIhhSvJL9ddi7Ul0pYehRDWK/22vOhWaoji7h9xeRY/roBMQEXYHgLgU9TjjqFnWo2O/2X6mKPDQzFsgtD+kdElHzXaFkTTqQhWWWW6gSPirKGPYtXUO2D/d8obCztl8WBzN/8ArVsNDaybug8jdnzz+vmU49PWY5qcQJEYkmUj9U+8J9MvLB36Qdw08QhhHPrNXx7jMYeQgUjLVwfml6g1Jna2Tso6qruN97Q/QdebSIcqXXmHZPXS29ZTm4v3MBJF2tRsFnORs6hHCbzZOuwELiy73JE9fMr4YCJfWRxumxeqeYgbyizipDEWRXC+Z8lmYyn3XY9DduAhwqfGud8s7moJ8CGlJrsGiFNvShBIw+P14qUtA9hxus7JY=}
